# Site configuration
title: Mohammed Ali's Blog
copyright_name: Mohammed Ali's Blog
description: "Welcome to the World of Programming"
baseurl: "Abstract-jekyll"
url: "https://xc0d3rz.github.io"
paginate: 5
category_dir: "categories"
category_layout: "category.html"
author:
    name: "Mohammed Ali"
    avatar: "/images/author.jpg"
    social:
        facebook: "xC0d3rZ.official"
        twitter: "xc0d3rz"
        instagram: "xc0d3rz"
        github: "xc0d3rz"
        email:  "x.c0d3rz000@gmail.com"
    bit: "Alias aperiam at debitis deserunt dignissimos dolorem doloribus, fuga fugiat impedit laudantium magni maxime nihil nisi quidem quisquam sed ullam voluptas voluptatum. Lorem ipsum dolor sit amet, consectetur adipisicing elit."
settings:
  disqus-id: "xc0d3rz"
gems :
  - jekyll-paginate
  - jekyll-paginate-category


